branches:
  only:
  - master
  - staging
  - trying
  - /^release\/.*$/ # release branches
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

language: julia

os:
  - linux
  - osx
  - windows

julia:
  - "1.3"
  - nightly
  
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
    - os: linux
      arch: x64
      julia: "1.3"
    - os: linux
      arch: x64
      julia: "nightly"
    - os: linux
      arch: x86
      julia: "1.3"
    - os: linux
      arch: x86
      julia: "nightly"
    - os: osx
      julia: "1.3"
    - os: osx
      julia: "nightly"
    - os: windows
      julia: "1.3"
    - os: windows
      julia: "nightly"

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
