branches:
  only:
  - master
  - staging
  - trying
  - /^release\/.*$/ # release branches
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

jobs:
  include:
    - os: windows
      arch: x64
      julia: 1.0
    - os: windows
      arch: x86
      julia: 1.0
      name: "Julia 1 (32bit)"
    - os: windows
      arch: x64
      julia: 1.1
    - os: windows
      arch: x86
      julia: 1.1
      name: "Julia 1.1 (32bit)"

julia:
  - "1.3"
  - nightly

language: julia

os:
  - linux
  - osx
  - windows

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
