# arch:
#   - "i386"
#   - "amd64"
#   - "arm64"

branches:
  only:
  - master
  - staging
  - trying
  - /^release\/.*$/ # release branches
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
    - os: linux
      arch: "amd64"
      julia: "1.3"
      name: "Linux 1.3 64-bit"
    - os: linux
      arch: "amd64"
      julia: nightly
      name: "Linux nightly 64-bit"
    - os: linux
      arch: "i386"
      julia: "1.3"
      name: "Linux 1.3 32-bit"
    - os: linux
      arch: "i386"
      julia: nightly
      name: "Linux nightly 32-bit"
    - os: linux
      arch: "arm64"
      julia: "1.3"
      name: "Linux 1.3 AArch64"
    - os: linux
      arch: "arm64"
      julia: nightly
      name: "Linux nightly AArch64"
    - os: osx
      arch: "amd64"
      julia: "1.3"
      name: "macOS 1.3"
    - os: osx
      arch: "amd64"
      julia: nightly
      name: "macOS nightly"
    - os: windows
      arch: "amd64"
      julia: "1.3"
      name: "Win 1.3 64-bit"
    - os: windows
      arch: "amd64"
      julia: nightly
      name: "Win nightly 64-bit"
    - os: windows
      arch: "i386"
      julia: "1.3"
      name: "Win 1.3 32-bit"
    - os: windows
      arch: "i386"
      julia: nightly
      name: "Win nightly 32-bit"

# julia:
#   - "1.3"
#   - nightly

language: julia

# os:
#   - linux
#   - osx
#   - windows

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
