arch:
  - "i386"
  - "amd64"
  - "arm64"

branches:
  only:
  - master
  - staging
  - trying
  - /^release\/.*$/ # release branches
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
    - os: windows
      arch: "i386"
      julia: "1.3"
    - os: windows
      arch: "i386"
      julia: nightly

julia:
  - "1.3"
  - nightly

language: julia

os:
  - linux
  - osx
  - windows

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
