arch:
  - "i386"
  - "amd64"
  - "arm64"

branches:
  only:
  - master
  - staging
  - trying
  - /^release\/.*$/ # release branches
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

jobs:
  allow_failures:
    # - julia: "nightly"
  fast_finish: true
  exclude:
    - os: linux
      arch: "arm64"
      julia: "nightly"
  include:
    - os: windows
      arch: "x86"
      julia: "1.3"
      name: "Julia 1.3 (32-bit)"
    - os: windows
      arch: "x86"
      julia: nightly
      name: "Julia nightly (32-bit)"

julia:
  - "1.3"
  - "nightly"

language: julia

os:
  - linux
  - osx
  - windows

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
