name = "GitCommand"
uuid = "49b5b516-ca3f-4003-a081-42bdcf55082d"
authors = ["Dilum Aluthge", "Brown Center for Biomedical Informatics"]
version = "0.3.0-DEV"

[deps]
Git_jll = "f8c6e375-362e-5223-8a59-34ff63f689eb"
ReplMaker = "b873ce64-0db9-51f5-a568-4457d8e49576"

[compat]
ReplMaker = "0.2.3"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
